---
- hosts: rails_app
  become: yes
  pre_tasks:
    - debug:
        msg: "{{ os_dep }}"
  roles:
    - geerlingguy.ruby
  tasks:
    - name: install dependencies
      include_tasks: tasks/ROR_OS_deps.yml
    - name: install telegraf
      include_tasks: tasks/telegraf.yml
    - name: deploy app
      include_tasks: tasks/app_config.yml

- hosts: metrics_storage
  become: yes
  tasks:
    - name: "install influxdb"
      include_tasks: tasks/influxdb.yml
    - name: "install grafana"
      include_tasks: tasks/grafana.yml

- hosts: proxy_server
  become: yes
  tasks:
    - name: configure proxy server
      include_tasks: tasks/proxy.yml
