---
- name: "install grafana"
  yum:
    name: "{{grafana_url}}"
    state: present
- name: "change grafana port if not changed"
  replace:
    path: /etc/grafana/grafana.ini
    regexp: ';http_port = 3000'
    replace: 'http_port = 8080'
- name: Grafana autoconfig
  grafana_datasource:
    name: "source_name"
    grafana_url: "http://127.0.0.1:8080"
    grafana_user: "admin"
    grafana_password: "admin"
    org_id: "1"
    ds_type: "influxdb"
    url: "http://127.0.0.1:8086"
    database: "metrics"
- service:
    name: grafana-server
    state: restarted
