---
- name: "install telegraf"
  yum:
    name: "{{telegraf_url}}"
    state: present
- template:
    src: conf/telegraf.conf
    dest: /etc/telegraf/telegraf.conf
- service:
    name: telegraf
    state: restarted
